### ISSUE TITLE
ff deploy show success, and then the container run error

### ISSUE THREAD

**Issue by 499909744** [hyperledger/firefly#1042]
**[root@hadoop203 contracts]# ff deploy fabric yljk yljk_action_log_1.tar.gz firefly yljk_action_log_1 1
installing chaincode
querying installed chaincode
approving chaincode
committing chaincode
{
  "chaincode": "yljk_action_log_1",
  "channel": "firefly"
}**

Thread[main,5,main] 02:15:35:957 INFO    org.hyperledger.fabric.contract.ContractRouter main                              Starting chaincode as client
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Thread[main,5,main] 02:15:36:093 SEVERE  org.hyperledger.fabric.contract.ContractRouter startRouting                      Invalid host or port: fabric_peer 7052
java.lang.IllegalArgumentException: Invalid host or port: fabric_peer 7052
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:520)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:134)
	at org.hyperledger.fabric.shim.ChaincodeBase.newChannelBuilder(ChaincodeBase.java:560)
	at org.hyperledger.fabric.shim.ChaincodeBase.connectToPeer(ChaincodeBase.java:178)
	at org.hyperledger.fabric.contract.ContractRouter.startRouting(ContractRouter.java:100)
	at org.hyperledger.fabric.contract.ContractRouter.main(ContractRouter.java:184)
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 8: //fabric_peer:7052
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3450)
	at java.base/java.net.URI$Parser.parseServer(URI.java:3299)
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3218)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3160)
	at java.base/java.net.URI$Parser.parse(URI.java:3127)
	at java.base/java.net.URI.<init>(URI.java:685)
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:518)
	... 5 more
.. caused by ..
Illegal character in hostname at index 8: //fabric_peer:7052
java.net.URISyntaxException: Illegal character in hostname at index 8: //fabric_peer:7052
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3450)
	at java.base/java.net.URI$Parser.parseServer(URI.java:3299)
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3218)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3160)
	at java.base/java.net.URI$Parser.parse(URI.java:3127)
	at java.base/java.net.URI.<init>(URI.java:685)
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:518)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:134)
	at org.hyperledger.fabric.shim.ChaincodeBase.newChannelBuilder(ChaincodeBase.java:560)
	at org.hyperledger.fabric.shim.ChaincodeBase.connectToPeer(ChaincodeBase.java:178)
	at org.hyperledger.fabric.contract.ContractRouter.startRouting(ContractRouter.java:100)
	at org.hyperledger.fabric.contract.ContractRouter.main(ContractRouter.java:184)

Exception in thread "main" org.hyperledger.fabric.contract.ContractRuntimeException: Unable to start routing
	at org.hyperledger.fabric.contract.ContractRouter.startRouting(ContractRouter.java:103)
	at org.hyperledger.fabric.contract.ContractRouter.main(ContractRouter.java:184)
Caused by: java.lang.IllegalArgumentException: Invalid host or port: fabric_peer 7052
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:520)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:134)
	at org.hyperledger.fabric.shim.ChaincodeBase.newChannelBuilder(ChaincodeBase.java:560)
	at org.hyperledger.fabric.shim.ChaincodeBase.connectToPeer(ChaincodeBase.java:178)
	at org.hyperledger.fabric.contract.ContractRouter.startRouting(ContractRouter.java:100)
	... 1 more
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 8: //fabric_peer:7052
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3450)
	at java.base/java.net.URI$Parser.parseServer(URI.java:3299)
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3218)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3160)
	at java.base/java.net.URI$Parser.parse(URI.java:3127)
	at java.base/java.net.URI.<init>(URI.java:685)
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:518)
	... 5 more

**Comment by 499909744** [comment]
the ccp.yaml peer port is 7051, shold i change it to 7052?
