### ISSUE TITLE
FireFly crash if a token pool event is received with an empty data string

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1121]
If "poolDataString" is an empty string and therefore "poolData" is nil, this line results in a nil pointer dereference.

https://github.com/hyperledger/firefly/blob/490745489fe98779cff07821d19ba7a83b8421bf/internal/tokens/fftokens/fftokens.go#L335

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xbef3d1]

goroutine 58 [running]:
github.com/hyperledger/firefly/internal/tokens/fftokens.(*FFTokens).handleTokenPoolCreate(0xc0002cf960, {0x1093520, 0xc0007e1ec0}, 0xc000d3a630, 0x0)
	/firefly/internal/tokens/fftokens/fftokens.go:335 +0x371
github.com/hyperledger/firefly/internal/tokens/fftokens.(*FFTokens).handleMessage(0xc0002cf960, {0x1093520, 0xc0007e1d00}, {0xc00087b000, 0x3f3, 0x400})
	/firefly/internal/tokens/fftokens/fftokens.go:511 +0x434
github.com/hyperledger/firefly/internal/tokens/fftokens.(*FFTokens).handleMessage(0xc0002cf960, {0x10935c8, 0xc00024d530}, {0xc000840100, 0x44c, 0x580})
	/firefly/internal/tokens/fftokens/fftokens.go:506 +0x878
github.com/hyperledger/firefly/internal/tokens/fftokens.(*FFTokens).eventLoop(0xc0002cf960)
	/firefly/internal/tokens/fftokens/fftokens.go:553 +0x28f
created by github.com/hyperledger/firefly/internal/tokens/fftokens.(*FFTokens).Init
	/firefly/internal/tokens/fftokens/fftokens.go:234 +0x296

```

**Comment by EleisonC** [comment]
Hello @awrichar I am new to hyperledger and would like to pick this issue up

**Comment by dwertent** [comment]
@EnriqueL8 It looks like this issue was resolved
