### ISSUE TITLE
Webhook-subscription to a listener for [blockchain_event] panics/crashes the respective FF-node, when processing the event

### ISSUE THREAD

**Issue by Rabax55** [hyperledger/firefly#1155]
# Bug Report

** FireFly-version ***
  "Version": "1.1.2",
  "Commit": "8b462fff760e1c7cc1d11c3ddb34638c094b0f2e",
  "Date": "2022-11-17T21:16:50Z",
  "License": "Apache-2.0"

** Current behavior: **
A webhook-subscription to a listener for [blockchain_event] panics/crashes the respective FF-node, when processing the event

** Expected behavior: **
The webhook-subscription should relay the [blockchain_event] to it's webhook-endpoint 

** Steps to reproduce: **
1. Create a new FF-stack - i called it "test_webhook" 
   -> 'ff init test_webhook 2 --prompt-names' (testcase 2 members name/node being 'org_00/n_org_00' and 'org_01/n_org_01')

2. Deploy a smart contract w/ a function emitting an event 
   -> for the test the notorious SimpleStorage.sol w/ event 'Changed' was used...

3. Define the smart contract ABI and Register contract API to the stack
   -> done via FF-Sandbox on node n_org_00
   -> Name of the contract API: 'SimpleStorage_100'

4. Register a contract listener  
   -> done via FF-Sandbox on node n_org_01
   -> listener name: 'SimpleStorage_100' (same for topic: and name:), 
      Event: 'Changed',
      firstEvent: 'oldest'

5. Create a subscription for the listener 'SimpleStorage_100', on node n_org_01    
   -> done via FF-System-API, like so:
      POST http://127.0.0.1:5001/api/v1/namespaces/default/subscriptions - w/ body:
      {
        "filter": {
          "blockchainevent": {
            "listener": "ce44e800-0938-469a-a7f7-ccf3e8d38974",
            "name": "Changed" 
          },
          "events": ".*",
          "message": {
            "author": ".*",
            "group": ".*",
            "tag": ".*"
          },
          "topic": ".*",
          "transaction": {
            "type": ".*"
          }
        },
        "name": "Org_01_TestWebhookFirefly",
        "namespace": "default",
        "options": {
          "fastack": true,
          "firstEvent": "oldest",
          "json": true,
          "readAhead": 65535,
          "reply": true,        
          "replytag": ".*",
          "replytx": ".*",
          "url": "http://<webhook-endpoint@>ngrok.io/<route>?<query-parm-1&<query-parm-2",
          "withData": false        
        },
        "transport": "webhooks"
      }
   -> The webhook-endpoint given in the "url"-parm works fine, when triggered via Postman

6. Call function 'set' of contract SimpleStorage
   -> done via generated Swagger-UI on node n_org_00, like so:
      http://127.0.0.1:5000/api/v1/namespaces/default/apis/SimpleStorage_100/api#//invoke_set
      {
        "input": {
          "newValue": "123"
        },
       "options": {}
      }

7. See the result on node n_org_01
   -> Log:
2023-01-20 19:51:51 [2023-01-20T18:51:51.368Z] DEBUG SQL<- query events ns=default pid=1 role=ep[default:6aed4d39-1e82-4e48-94fd-0736c4a2cf04]
2023-01-20 19:51:51 [2023-01-20T18:51:51.368Z] DEBUG Dispatcher event state: readahead=65535 candidates=1 matched=1 inflight=0 queued=0 dispatched=0 dispatchable=1 lastAck=0 nacks=0 highest=21 ns=default pid=1 role=ed[JkKTYDnN] sub=7cc75379-203a-4df7-921b-ddea2346163d/default:Org_01_TestWebho...
2023-01-20 19:51:51 [2023-01-20T18:51:51.368Z] DEBUG Dispatching webhooks event: 0000000021/879aa033-883e-4133-8ea6-d47270e387ef [blockchain_event_received]: ref=default/96cc16e6-8ac7-4d2f-b3b9-ed0ff9ad3423 ns=default pid=1 role=ed[JkKTYDnN] sub=7cc75379-203a-4df7-921b-ddea2346163d/default:Org_01_TestWebho...
2023-01-20 19:51:51 [2023-01-20T18:51:51.368Z] DEBUG SQL-> query events ns=default pid=1 role=ep[default:88ec6b0f-77aa-4209-92f9-bad170561bc7]
2023-01-20 19:51:51 panic: runtime error: invalid memory address or nil pointer dereference
2023-01-20 19:51:51 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa9b897]
2023-01-20 19:51:51 
2023-01-20 19:51:51 goroutine 1885 [running]:
2023-01-20 19:51:51 github.com/hyperledger/firefly/internal/events/webhooks.(*WebHooks).DeliveryRequest(0x16419a0, {0xc00003d720, 0x8}, 0xc000bc2000, 0xc000302540, {0x0?, 0x0, 0x0})
2023-01-20 19:51:51     /firefly/internal/events/webhooks/webhooks.go:342 +0x197
2023-01-20 19:51:51 github.com/hyperledger/firefly/internal/events.(*eventDispatcher).deliverEvents(0xc000bca000)
2023-01-20 19:51:51     /firefly/internal/events/event_dispatcher.go:381 +0x2f3
2023-01-20 19:51:51 created by github.com/hyperledger/firefly/internal/events.(*eventDispatcher).electAndStart
2023-01-20 19:51:51     /firefly/internal/events/event_dispatcher.go:151 +0x225

** Related code: **
The full log of node n_org_01 is attached
[Node_n_org_01_Full_Log_up_to_Panic.txt](https://github.com/hyperledger/firefly/files/10469266/Node_n_org_01_Full_Log_up_to_Panic.txt)

** Other information: **
There is a side-flaw in the FF-System-Api wrt the subscription option "withData"=true. As per @Nicko Guyer 'true' is not supported for custom contract events (atm). 
If this this option/parm is used when creating a 'websocket'-subscription, the Api accordingly returns an "error": "FF10244: Websockets subscriptions do not support streaming the full data payload, just the references (withData must be false)". This is not the case, when creating a 'webhook'-subscription (resulting in a sub-scription that just does nothing at all...). 
This as well should be fixed...

**Comment by nguyer** [comment]
Thanks for reporting this. I will see if I can reproduce this in `main`

**Comment by nguyer** [comment]
I was able to verify this both in `main` and `v1.1.2` so this definitely needs to get fixed.

The issue is when `"reply": true` is set, it looks for a Message on the event. In the case of a custom contract event there is none so it gets a `nil` pointer.

**Comment by Rabax55** [comment]
Ok. Would that mean, that with "reply": false one would get different behavior?

**Comment by nguyer** [comment]
Yes, as a workaround for now you can set `"reply": false`, or omit it entirely and it will avoid the panic.

I have a fix for this already, but there are a few more things that also need to be cleaned up in related code. The fix will be in the next v1.2.0 alpha.

**Comment by Rabax55** [comment]
Yep, can confirm. Very different behavior:

a) on the subscribed node:
2023-01-20 22:38:48 [2023-01-20T21:38:48.932Z]  INFO <-- POST /api/v0/swarm/peers [404] (0.08ms): FF10109: Not found httpreq=A0w9Ku1e pid=1 req=26LTmhtb
2023-01-20 22:38:50 [2023-01-20T21:38:50.250Z]  INFO Webhook<- POST http://<webhook-endpoint@>ngrok.io/<route>?<query-1>&<query-> event f8bd5b6c-1a23-417f-a962-cf656eafcc2e on subscription 5feba54b-fbab-4341-b7b0-9b88a3424251 returned 200 pid=1 webhook=
2023-01-20 22:38:50 [2023-01-20T21:38:50.250Z] DEBUG Response content-type 'text/html' forceJSON=true pid=1 webhook=
2023-01-20 22:38:50 [2023-01-20T21:38:50.250Z] ERROR Failed to invoke webhook: FF10257: Failed to process reply from webhook as JSON: EOF pid=1 webhook=
2023-01-20 22:38:50 [2023-01-20T21:38:50.250Z]  WARN Webhook delivery failed in fastack mode for event 'f8bd5b6c-1a23-417f-a962-cf656eafcc2e': %!s(<nil>) pid=1 webhook=
2023-01-20 22:38:51 [2023-01-20T21:38:51.522Z] DEBUG Woken after poll timeout ns=default pid=1 role=batchmgr

where it's certainly "FF10257: Failed to process reply from webhook as JSON: EOF pid=1 webhook=", 
but not so  "ERROR Failed to invoke webhook", 
bc

b) Webhook gets triggered:
{
    "id": "f8bd5b6c-1a23-417f-a962-cf656eafcc2e",
    "sequence": 21,
    "type": "blockchain_event_received",
    "namespace": "default",
    "reference": "60bbc848-1d74-4566-8795-0bcb9f8fd0bc",
    "topic": "SimpleStorage_Changed",
    "created": "2023-01-20T21:38:44.805429279Z",
    "blockchainEvent": {
        "id": "60bbc848-1d74-4566-8795-0bcb9f8fd0bc",
        "source": "ethereum",
        "namespace": "default",
        "name": "Changed",
        "listener": "ea6141ce-f551-4bea-9b59-df2db5ae4374",
        "protocolId": "000000001398/000000/000000",
        "output": {
            "from": "0x088bd4f6f48b8d765ca0ccf7be0c5055dc546c5e",
            "value": "123"
        },
        "info": {
            "address": "0xc133ff7c280973B98363753F4B37b5aC380eb969",
            "blockHash": "0x957406b08a2549958329eee1d7a7f8aa593d6ee0a48be39473fa07294c76e822",
            "blockNumber": "1398",
            "logIndex": "0",
            "signature": "Changed(address,uint256)",
            "subId": "sb-07ddeaf5-9d3f-4d29-58e4-93b8170f5bb8",
            "timestamp": "1674250723",
            "transactionHash": "0xd3984b451aed2f99d85c56a4dc54e508f0fa29836abe0ed84f13309364f5ca44",
            "transactionIndex": "0x0"
        },
        "timestamp": "2023-01-20T21:38:43Z",
        "tx": {
            "blockchainId": "0xd3984b451aed2f99d85c56a4dc54e508f0fa29836abe0ed84f13309364f5ca44"
        }
    },
    "subscription": {
        "id": "5feba54b-fbab-4341-b7b0-9b88a3424251",
        "namespace": "default",
        "name": "Org_01_TestWebhookFirefly"
    }
}

**Comment by Rabax55** [comment]
Should the detected "side"-flaw during testing:

There is a side-flaw in the FF-System-Api wrt the subscription option "withData"=true. As per @Nicko Guyer 'true' is not supported for custom contract events (atm).
If this this option/parm is used when creating a 'websocket'-subscription, the Api accordingly returns an "error": "FF10244: Websockets subscriptions do not support streaming the full data payload, just the references (withData must be false)". This is not the case, when creating a 'webhook'-subscription (resulting in a sub-scription that just does nothing at all...).
This as well should be fixed...

be opened as a separate issue?
