### ISSUE TITLE
Intermittent E2E test failure - `concurrent map writes`

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#1272]
```
[34mfirefly_core_0_1  |[0m fatal error: concurrent map writes
[34mfirefly_core_0_1  |[0m 
[34mfirefly_core_0_1  |[0m goroutine 9683 [running]:
[34mfirefly_core_0_1  |[0m runtime.throw({0xf4dffa?, 0xe0?})
[34mfirefly_core_0_1  |[0m 	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000817630 sp=0xc000817600 pc=0x440e11
[34mfirefly_core_0_1  |[0m runtime.mapassign_faststr(0xc0008176c0?, 0x416447?, {0xc000c83c20, 0x10})
[34mfirefly_core_0_1  |[0m 	/usr/local/go/src/runtime/map_faststr.go:212 +0x39c fp=0xc000817698 sp=0xc000817630 pc=0x41c09c
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/events/webhooks.(*WebHooks).SetHandler(0x1681c20, {0xc000c83c20?, 0xc000817710?}, {0x10bfcd8?, 0xc000d18d20})
[34mfirefly_core_0_1  |[0m 	/firefly/internal/events/webhooks/webhooks.go:78 +0x50 fp=0xc0008176d0 sp=0xc000817698 pc=0xb312b0
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/events.newSubscriptionManager({0x10bfa00?, 0xc000c7e440?}, {0xc000c83c20, 0x10}, 0xc000655360, {0x10ca3b8?, 0xc000abbc20}, {0x10c4a28?, 0xc0003783f0}, 0xc000130b40, ...)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/events/subscription_manager.go:122 +0x512 fp=0xc0008177e8 sp=0xc0008176d0 pc=0xb68472
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/events.NewEventManager({0x10bfa00?, 0xc000c7e440}, 0xc0000c1340, {0x10ca3b8, 0xc000abbc20}, {_, _}, {_, _}, {0x10b9620, ...}, ...)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/events/event_manager.go:175 +0xc3c fp=0xc000817958 sp=0xc0008177e8 pc=0xb6089c
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/orchestrator.(*orchestrator).initComponents(0xc000622d80, {0x10bfa00, 0xc000c7e440})
[34mfirefly_core_0_1  |[0m 	/firefly/internal/orchestrator/orchestrator.go:524 +0x3dd fp=0xc000817b10 sp=0xc000817958 pc=0xb7b7bd
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/orchestrator.(*orchestrator).Init(0xc000622d80, {0x10bfa00?, 0xc000c7e400?}, 0x11?)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/orchestrator/orchestrator.go:232 +0x12f fp=0xc000817b68 sp=0xc000817b10 pc=0xb7924f
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).initNamespace(0xc0005281c0, 0xc0000c1340)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/namespace/manager.go:362 +0x42c fp=0xc000817d40 sp=0xc000817b68 pc=0xc1786c
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).initAndStartNamespace(0xc0005281c0, 0xc0000c1340)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/namespace/manager.go:317 +0x3b fp=0xc000817df8 sp=0xc000817d40 pc=0xc1721b
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).namespaceStarter.func1(0x7f4c5dd78108?)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/namespace/manager.go:297 +0x3d fp=0xc000817e88 sp=0xc000817df8 pc=0xc16ffd
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly-common/pkg/retry.(*Retry).Do(0xc000b173c0, {0x10bfa00, 0xc0002eb0c0}, {0xc000e97c60, 0x1a}, 0xc000817f98)
[34mfirefly_core_0_1  |[0m 	/go/pkg/mod/github.com/hyperledger/firefly-common@v1.2.3/pkg/retry/retry.go:56 +0xe4 fp=0xc000817f58 sp=0xc000817e88 pc=0x9597e4
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).namespaceStarter(0xc0005281c0, 0xc0000c1340)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/namespace/manager.go:296 +0xc5 fp=0xc000817fc0 sp=0xc000817f58 pc=0xc16f85
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).startNamespacesAndPlugins.func1()
[34mfirefly_core_0_1  |[0m 	/firefly/internal/namespace/manager.go:385 +0x2a fp=0xc000817fe0 sp=0xc000817fc0 pc=0xc17daa
[34mfirefly_core_0_1  |[0m runtime.goexit()
[34mfirefly_core_0_1  |[0m 	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000817fe8 sp=0xc000817fe0 pc=0x473b81
[34mfirefly_core_0_1  |[0m created by github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).startNamespacesAndPlugins
[34mfirefly_core_0_1  |[0m 	/firefly/internal/namespace/manager.go:385 +0x6e
```

[logs 16.txt](https://github.com/hyperledger/firefly/files/11236701/logs.16.txt)

**Comment by peterbroadhurst** [comment]
Confident this is unrelated to https://github.com/hyperledger/firefly/issues/1272, but will look into it under the scope of https://github.com/hyperledger/firefly/pull/1242
