### ISSUE TITLE
Integration Test failure - PostgreSQL migrations broken

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#415]
```
[34mfirefly_core_0_1  |[0m Error: FF10163: Database migration failed: FF10163: Database migration failed: migration failed: syntax error at or near "AUTOINCREMENT" (column 48) in line 3: BEGIN;
[34mfirefly_core_0_1  |[0m CREATE TABLE blockchainevents (
[34mfirefly_core_0_1  |[0m   seq              INTEGER         PRIMARY KEY AUTOINCREMENT,
[34mfirefly_core_0_1  |[0m   id               UUID            NOT NULL,
[34mfirefly_core_0_1  |[0m   source           VARCHAR(256)    NOT NULL,
[34mfirefly_core_0_1  |[0m   namespace        VARCHAR(64)     NOT NULL,
[34mfirefly_core_0_1  |[0m   name             VARCHAR(256)    NOT NULL,
[34mfirefly_core_0_1  |[0m   protocol_id      VARCHAR(256)    NOT NULL,
[34mfirefly_core_0_1  |[0m   timestamp        BIGINT          NOT NULL,
[34mfirefly_core_0_1  |[0m   subscription_id  UUID,
[34mfirefly_core_0_1  |[0m   output           BYTEA,
[34mfirefly_core_0_1  |[0m   info             BYTEA,
[34mfirefly_core_0_1  |[0m   tx_type          VARCHAR(64),
[34mfirefly_core_0_1  |[0m   tx_id            UUID
[34mfirefly_core_0_1  |[0m );
[34mfirefly_core_0_1  |[0m 
```

https://github.com/hyperledger/firefly/actions/runs/1710533036

**Comment by peterbroadhurst** [comment]
Going to take a look at this

**Comment by peterbroadhurst** [comment]
After that patch, I hit:
```
firefly_core_0_1  | [2022-01-19T14:26:41.318Z] ERROR WS ws://ethconnect_0:8080/ws closed: read tcp 172.26.0.14:38476->172.26.0.11:8080: use of closed network connection pid=1
firefly_core_0_1  | [2022-01-19T14:26:41.318Z] DEBUG WS ws://ethconnect_0:8080/ws close failed: close tcp 172.26.0.14:38476->172.26.0.11:8080: use of closed network connection pid=1
firefly_core_0_1  | panic: interface conversion: interface {} is string, not []uint8
firefly_core_0_1  | 
firefly_core_0_1  | goroutine 260 [running]:
firefly_core_0_1  | github.com/hyperledger/firefly/pkg/fftypes.(*JSONObject).Scan(0xc00019eb20, 0xe35d80, 0xc0003d0d60, 0x7f3e5ad94260, 0xc00019eb20)
firefly_core_0_1  | 	/firefly/pkg/fftypes/jsonobject.go:44 +0x26e
firefly_core_0_1  | database/sql.convertAssignRows(0xf26140, 0xc00019eb20, 0xe35d80, 0xc0003d0d60, 0xc0000eec00, 0x0, 0x0)
firefly_core_0_1  | 	/usr/local/go/src/database/sql/convert.go:385 +0x181d
firefly_core_0_1  | database/sql.(*Rows).Scan(0xc0000eec00, 0xc0008f3940, 0xc, 0xc, 0xc00019ec80, 0xc0000f4840)
firefly_core_0_1  | 	/usr/local/go/src/database/sql/sql.go:3144 +0x265
firefly_core_0_1  | github.com/hyperledger/firefly/internal/database/sqlcommon.(*SQLCommon).opResult(0x162cd40, 0x10c9f78, 0xc00055f350, 0xc0000eec00, 0x10d1de0, 0xc0007b4000, 0xc0000eec00)
firefly_core_0_1  | 	/firefly/internal/database/sqlcommon/operation_sql.go:89 +0x1b6
firefly_core_0_1  | github.com/hyperledger/firefly/internal/database/sqlcommon.(*SQLCommon).GetOperationByID(0x162cd40, 0x10c9f78, 0xc00055f350, 0xc00003a920, 0x0, 0x0, 0x0)
firefly_core_0_1  | 	/firefly/internal/database/sqlcommon/operation_sql.go:126 +0x35e
firefly_core_0_1  | github.com/hyperledger/firefly/internal/events.(*eventManager).OperationUpdate(0xc00001a500, 0x7f3e5ad94240, 0x162d340, 0xc00003a920, 0xf8807b, 0x9, 0x0, 0x0, 0xc00056d170, 0xc0007a2160, ...)
firefly_core_0_1  | 	/firefly/internal/events/operation_update.go:26 +0x6a
firefly_core_0_1  | github.com/hyperledger/firefly/internal/orchestrator.(*boundCallbacks).BlockchainOpUpdate(0xc0003dd628, 0xc00003a920, 0xf8807b, 0x9, 0x0, 0x0, 0xc00056d170, 0x0, 0x2a8)
firefly_core_0_1  | 	/firefly/internal/orchestrator/bound_callbacks.go:34 +0xcf
firefly_core_0_1  | github.com/hyperledger/firefly/internal/blockchain/ethereum.(*Ethereum).handleReceipt(0x162d340, 0x10c9f78, 0xc0005051d0, 0xc00056d170, 0xc0007b20c0, 0x0)
firefly_core_0_1  | 	/firefly/internal/blockchain/ethereum/ethereum.go:325 +0x46d
firefly_core_0_1  | github.com/hyperledger/firefly/internal/blockchain/ethereum.(*Ethereum).eventLoop(0x162d340)
firefly_core_0_1  | 	/firefly/internal/blockchain/ethereum/ethereum.go:393 +0x639
firefly_core_0_1  | created by github.com/hyperledger/firefly/internal/blockchain/ethereum.(*Ethereum).Init
firefly_core_0_1  | 	/firefly/internal/blockchain/ethereum/ethereum.go:154 +0x71f
```

**Comment by peterbroadhurst** [comment]
The `JSONObject` scan function wasn't set up for `string`, and looks like SQLite always returns `[]byte` (regardless of TEXT or BLOB type)

**Comment by peterbroadhurst** [comment]
Then hit:

```
    restclient.go:71: <== 400
    restclient.go:73: <!! {"error":"FF10315: Unable to resolve contract method"}
    restclient.go:74: Headers: map[Content-Length:[55] Content-Type:[application/json] Date:[Wed, 19 Jan 2022 17:09:25 GMT] Vary:[Origin]]
    restclient.go:551: 
        	Error Trace:	restclient.go:551
        	            				ethereum_contract_test.go:323
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 400
        	Test:       	TestEthereumE2ESuite/TestFFIInvokeMethod
        	Messages:   	POST /namespaces/default/contracts/interfaces/d6b27311-31e4-4ea7-a2b7-0f2105c1a723/invoke/set [400]: {"error":"FF10315: Unable to resolve contract method"}
    e2e_test.go:259: Websocket 127.0.0.1:5000 closing, error: read tcp 127.0.0.1:52065->127.0.0.1:5000: use of closed network connection
    e2e_test.go:247: WebSockets closed

```

**Comment by peterbroadhurst** [comment]
Think this is actually another instance of the `string`/`[]byte` issue, but `FF10315` was missing the error insert. So I've added the insert there.

**Comment by peterbroadhurst** [comment]
Yup, full error was:
`FF10315: Unable to resolve contract method: FF10121: Database resultset read error from table 'ffimethods': sql: Scan error on column index 6, name \u0026#34;params\u0026#34;: FF10125: Failed to restore type 'string' into '*fftypes.FFIParams'`
