### ISSUE TITLE
Segmentation violation during restart in integration test

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly#979]
During last night's integration suite run, the [EthMultiparty/Besu/Postgres](https://github.com/hyperledger/firefly/runs/7890809486?check_suite_focus=true#step:6:1166) run failed due to a segmentation violation while shutting down for a restart

Log snippet:
```
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z]  INFO Restarting due to configuration change pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z]  INFO Terminated namespace 'default' pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z] DEBUG New event notifier loop ending (context cancelled) ns=default pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z] DEBUG event notifier closing ns=default pid=1 role=ep[default:f87be208-dc12-4bf2-bd31-8504712ed7a6]
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z] DEBUG Exiting due to cancelled context ns=default pid=1 role=ep[default:ff_aggregator]
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z] DEBUG New event notifier loop ending (context cancelled) ns=default pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z] DEBUG event notifier closing ns=default pid=1 role=ep[default:ff_aggregator]
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z] DEBUG Rewind Processor Loop stopping ns=default pid=1 role=aggregator-rewind
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.677Z] DEBUG Rewind Receiver Loop stopping ns=default pid=1 role=aggregator-rewind
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.761Z]  INFO Terminated namespace 'e2e_d64ca8232e' pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.761Z] DEBUG New event notifier loop ending (context cancelled) ns=e2e_d64ca8232e pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.761Z] DEBUG New event notifier loop ending (context cancelled) ns=e2e_d64ca8232e pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.761Z] DEBUG Closing 0 dispatcher(s) for connection 'hNlN6moG' ns=e2e_d64ca8232e pid=1
[34mfirefly_core_0_1  |[0m [2022-08-18T02:12:54.761Z] DEBUG Closing 0 dispatcher(s) for connection 'cooLfV0J' ns=e2e_d64ca8232e pid=1
[34mfirefly_core_0_1  |[0m panic: runtime error: invalid memory address or nil pointer dereference
[34mfirefly_core_0_1  |[0m [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xab1199]
[34mfirefly_core_0_1  |[0m 
[34mfirefly_core_0_1  |[0m goroutine 1 [running]:
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/events.(*blobReceiver).stop(0x0)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/events/blob_receiver.go:122 +0x19
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/events.(*eventManager).WaitStop(0xc00015c000)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/events/event_manager.go:201 +0x39
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/orchestrator.(*orchestrator).WaitStop(0xc00044c900)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/orchestrator/orchestrator.go:299 +0x19b
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/internal/namespace.(*namespaceManager).WaitStop(0xc0000d6e70)
[34mfirefly_core_0_1  |[0m 	/firefly/internal/namespace/manager.go:357 +0x1e4
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/cmd.run()
[34mfirefly_core_0_1  |[0m 	/firefly/cmd/firefly.go:138 +0x5a2
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/cmd.glob..func1(0x15dbde0, {0xed46dc, 0x0, 0x0})
[34mfirefly_core_0_1  |[0m 	/firefly/cmd/firefly.go:51 +0x17
[34mfirefly_core_0_1  |[0m github.com/spf13/cobra.(*Command).execute(0x15dbde0, {0xc0000921e0, 0x0, 0x0})
[34mfirefly_core_0_1  |[0m 	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
[34mfirefly_core_0_1  |[0m github.com/spf13/cobra.(*Command).ExecuteC(0x15dbde0)
[34mfirefly_core_0_1  |[0m 	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
[34mfirefly_core_0_1  |[0m github.com/spf13/cobra.(*Command).Execute(...)
[34mfirefly_core_0_1  |[0m 	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
[34mfirefly_core_0_1  |[0m github.com/hyperledger/firefly/cmd.Execute(...)
[34mfirefly_core_0_1  |[0m 	/firefly/cmd/firefly.go:97
[34mfirefly_core_0_1  |[0m main.main()
[34mfirefly_core_0_1  |[0m 	/firefly/main.go:27 +0x25
```

**Comment by shorsher** [comment]
Container logs:

[multiparty:besu:postgres-fail-log.txt](https://github.com/hyperledger/firefly/files/9375445/multiparty.besu.postgres-fail-log.txt)

**Comment by shorsher** [comment]
[4_e2e-test (TestEthereumMultipartyE2ESuite, besu, postgres).txt](https://github.com/hyperledger/firefly/files/9375457/4_e2e-test.TestEthereumMultipartyE2ESuite.besu.postgres.txt)
